// Generated by LiveScript 1.4.0
(function(){
  describe('fun', function(){
    var fishLibLs, test, xtest;
    fishLibLs = require('../index');
    test = global.it;
    xtest = global.xit;
    beforeEach(function(done){
      return console.log('hi');
    });
    return test('start', function(){
      return expect(19).toEqual(19);
    });
  });
}).call(this);
