// Generated by LiveScript 1.4.0
(function(){
  var fs, path, sprintf, Obj, fishLibLs, test, xtest, dir;
  fs = require('fs');
  path = require('path');
  sprintf = require('sprintf');
  Obj = require('prelude-ls').Obj;
  fishLibLs = require('../index');
  test = global.it;
  xtest = global.xit;
  dir = {};
  dir.bin = path.dirname(process.argv[1]);
  dir.spec = dir.bin + '/../spec';
  dir.test = dir.spec + '/data/sysSpec';
  dir = Obj.map(path.resolve, dir);
  init();
  describe('sys-exec', function(){
    var cmd;
    beforeEach(function(done){
      return done();
    });
    cmd = sprintf('ls -Q "%s"/*.txt | xargs cat | wc -w', dir.test);
    xtest('string', function(done){
      return fishLibLs.sysExec(cmd);
    });
    return test('string, object', function(done){
      return fishLibLs.sysExec(cmd, {
        oncomplete: function(arg$){
          var out, ok;
          out = arg$.out, ok = arg$.ok;
          if (!ok) {
            error();
          }
          expect(out.trim()).toEqual('12');
          return done();
        }
      });
    });
  });
  function init(){}
  function log(){
    return console.log.apply(console, arguments);
  }
}).call(this);
